# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
---
include:
  # Dongle central
  - board: raytac_mdbt50q_cx_40_dongle/nrf52840
    shield: zonkey_dongle
    artifact-name: zonkey_dongle

  # Left peripheral
  - board: seeeduino_xiao_ble
    shield: zonkey_L rgbled_adapter
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: zonkey_left_peripheral

  # Right peripheral (以前は central だったが peripheral に落とす)
  - board: seeeduino_xiao_ble
    shield: zonkey_R rgbled_adapter
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: zonkey_right_peripheral

  # Settings reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: settings_reset_xiao

  - board: raytac_mdbt50q_cx_40_dongle/nrf52840
    shield: settings_reset
    artifact-name: settings_reset_raytac