name: Build ZMK Firmware

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Zephyr環境セットアップ
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git cmake ninja-build gperf \
            ccache dfu-util device-tree-compiler \
            wget python3-pip python3-setuptools python3-wheel \
            xz-utils file make gcc gcc-multilib g++-multilib \
            libsdl2-dev libmagic1

      - name: Install west
        run: pip install west

      - name: Init west
        run: |
          west init -l config
          west update
          west zephyr-export

      - name: Install Python deps
        run: pip install -r zephyr/scripts/requirements.txt

      - name: Build firmware
        run: |
          mkdir -p build artifacts

          COUNT=$(yq '.include | length' build.yaml)

          for ((i=0; i<COUNT; i++)); do
            BOARD=$(yq ".include[$i].board" build.yaml)
            SHIELD=$(yq ".include[$i].shield" build.yaml)
            ARGS=$(yq ".include[$i].cmake-args // \"\"" build.yaml)
            ARTIFACT=$(yq ".include[$i].artifact-name // \"firmware\"" build.yaml)

            BUILD_DIR=build/${ARTIFACT}

            echo "======================================"
            echo "Building ${ARTIFACT}"
            echo "BOARD=${BOARD}"
            echo "SHIELD=${SHIELD}"
            echo "======================================"

            west build -s zmk/app -d ${BUILD_DIR} -b ${BOARD} -- \
              -DZMK_CONFIG=${GITHUB_WORKSPACE}/config \
              -DSHIELD="${SHIELD}" ${ARGS}

            echo "==== FILE LIST (${ARTIFACT}) ===="
            find "${BUILD_DIR}" -type f

            # dongleのみhex
            if [[ "$ARTIFACT" == "zonkey_dongle" ]]; then
              HEX_FILE=$(find "${BUILD_DIR}" -name "*.hex" | head -n 1)

              if [ -n "${HEX_FILE}" ]; then
                cp "${HEX_FILE}" "artifacts/${ARTIFACT}.hex"
                echo "Copied HEX: ${HEX_FILE}"
              else
                echo "ERROR: hex not found"
                exit 1
              fi
            fi

            # UF2（左右）
            UF2_FILE=$(find "${BUILD_DIR}" -name "*.uf2" | head -n 1)
            if [ -n "${UF2_FILE}" ]; then
              cp "${UF2_FILE}" "artifacts/${ARTIFACT}.uf2"
              echo "Copied UF2: ${UF2_FILE}"
            fi

          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: artifacts/